version: 0.2
env:
  parameter-store:
    DB_HOST: /CodeBuild/DB_HOST
    DB_USER: /CodeBuild/DB_USER
    DB_PASSWORD: /CodeBuild/DB_PASSWORD
    DATABASE: /CodeBuild/DATABASE
    JWT_SECRET: /CodeBuild/JWT_SECRET
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install 
      - npm install -g serverless 
      - export DB_HOST=$DB_HOST
      - export DB_USER=$DB_USER
      - export DB_PASSWORD=$DB_PASSWORD
      - export DATABASE=$DATABASE
      - export JWT_SECRET=$JWT_SECRET
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR_EnvArtifact
      - cp .env $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - serverless deploy 
